version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'chat_server'
      MYSQL_USER: 'chat'
      MYSQL_PASSWORD: 'avito'
      MYSQL_ROOT_PASSWORD: 'password'
  web:
    depends_on:
      - db
    image: chat_server
    build: .
    command: sh -c './wait_for.sh db:3306 -- python /code/chat_server/manage.py runserver 0.0.0.0:9000'
    volumes:
      - .:/code
    ports:
      - "9000:9000"
  migration:
    depends_on:
      - db
    build: .
    image: chat_server
    command: sh -c './wait_for.sh db:3306 -- python /code/chat_server/manage.py migrate'
    volumes:
      - .:/code
    links:
      - db
      